# Generated by Django 5.0.6 on 2024-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("photo_url", models.CharField(max_length=255)),
                ("goods_url", models.CharField(max_length=255)),
                ("items", models.IntegerField()),
                ("create_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "goods",
            },
        ),
        migrations.CreateModel(
            name="GoodsItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemName", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "items",
            },
        ),
    ]
