# Generated by Django 5.0.6 on 2024-05-25 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailmodel",
            old_name="quatity",
            new_name="quantity",
        ),
    ]
